Ellen satellite info
SOEP-Group/SOEP-Visualizer pull request #14
Opened 2024-09-19 14:10 UTC by Limeiz

Added new earths (within size limit)
User gets shown earth pic of current month
Added popup with mock data (not stylized)
Set scroll lock so user can't zoom through earth

2024-09-20 06:36 UTC, mohammed-shakir reviewed
I am not the best js developer so i think its better if @RyuTribal  took a look into this. I added a few comments on things that need to be fixed but its nothing major, i pulled the code and tested it, it looks really nice, good job :)

But yeah i would wait until you get a second review until we merge this pr, just in case :)

2024-09-20 06:36 UTC, mohammed-shakir commented on public/index.html
Create a separate CSS file for styling

2024-09-20 06:36 UTC, mohammed-shakir commented on public/main.js
> +function fetchSatelliteData() {
Add a fallback/error-handling to these two functions (in case the networking goes wrong or something else)

2024-09-20 06:36 UTC, mohammed-shakir commented on public/popup.js
Duplicate code: fetch('/views/popup.html')...

2024-09-20 06:44 UTC, sanlju approved these changes
LGTM! I added a css directory on another branch so we can have all style in those later.

2024-09-22 11:07 UTC, RyuTribal commented
Looks good, I just have a few concerns and questions.

- I see we now have different textures for earth at different times, I'm just not sure of the difference, because if it's a difference in shading, we could try to achieve that with the directional light we have made.
- The mock data is fine for testing, but if you would like to simulate a more realistic approach to how we are gonna fetch the data and such, I would recommend to fetch a group of id's from the back-end (or return an html list with the data, a bit hard since we do not have a templating engine yet, but you could build it up in a string at the time). After a click is done, you can fetch the rest of the data
- The way we draw satellites is fine for now, but it will quickly spiral out and drop our performance when going above a thousand or so. When it comes to drawing geometry that is exactly the same but with a few differences (position, color), your best approach is to use [Instanced rendering](https://threejs.org/docs/#api/en/objects/InstancedMesh)

2024-09-22 11:08 UTC, RyuTribal requested changes
Check my comment above

2024-09-23 15:36 UTC, Limeiz commented on public/index.html
Fixed on other branch, will merge it in

2024-09-23 15:48 UTC, Limeiz commented
> Looks good, I just have a few concerns and questions.
> 
> * I see we now have different textures for earth at different times, I'm just not sure of the difference, because if it's a difference in shading, we could try to achieve that with the directional light we have made.
> * The mock data is fine for testing, but if you would like to simulate a more realistic approach to how we are gonna fetch the data and such, I would recommend to fetch a group of id's from the back-end (or return an html list with the data, a bit hard since we do not have a templating engine yet, but you could build it up in a string at the time). After a click is done, you can fetch the rest of the data
> * The way we draw satellites is fine for now, but it will quickly spiral out and drop our performance when going above a thousand or so. When it comes to drawing geometry that is exactly the same but with a few differences (position, color), your best approach is to use [Instanced rendering](https://threejs.org/docs/#api/en/objects/InstancedMesh)

Different textures, solved

Moved the instanced rendering to this issue, so it will be addressed there instead https://github.com/SOEP-Group/SOEP-Visualizer/issues/5#issue-2528478526

Will work on the second point, fetching data from the backend and test that

2024-09-23 16:53 UTC, mohammed-shakir commented
Left to do on this branch:
1. Fix this point that Ivan brought up:
- The mock data is fine for testing, but if you would like to simulate a more realistic approach to how we are gonna fetch the data and such, I would recommend to fetch a group of id's from the back-end (or return an html list with the data, a bit hard since we do not have a templating engine yet, but you could build it up in a string at the time). After a click is done, you can fetch the rest of the data

2. Merge with @sanlju branch called "design"

2024-09-30 14:31 UTC, closed without merging